on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.6.5
          - 2.7.0
          - 3.0.0
          - 3.1.0
        gemfile:
          - gemfiles/activesupport_2.3_LTS.gemfile
          - gemfiles/activesupport_3.gemfile
          - gemfiles/activesupport_4.gemfile
          - gemfiles/activesupport_5.gemfile
          - gemfiles/activesupport_6.gemfile
          - gemfiles/activesupport_7.gemfile
        exclude:
          - ruby: 2.6.5
            gemfile: gemfiles/activesupport_7.gemfile
          - ruby: 2.7.0
            gemfile: gemfiles/activesupport_3.gemfile
          - ruby: 2.7.0
            gemfile: gemfiles/activesupport_4.gemfile
          - ruby: 3.0.0
            gemfile: gemfiles/activesupport_3.gemfile
          - ruby: 3.0.0
            gemfile: gemfiles/activesupport_4.gemfile
          - ruby: 3.1.0
            gemfile: gemfiles/activesupport_3.gemfile
          - ruby: 3.1.0
            gemfile: gemfiles/activesupport_4.gemfile

    name: Ruby ${{ matrix.ruby }} using Gemfile ${{ matrix.gemfile }}
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: 'Update gem command'
        run: yes | gem update --system --force
      - name: 'Update Bundler'
        run: gem install bundler
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - run: bundle install
      - run: bundle exec rake
